/**
 * load-tests/concurrency.js  —  THE MAIN CONCURRENCY TEST
 *
 * Sends 100 simultaneous POST /holds requests for a 20-seat workshop.
 * This directly tests the task requirement:
 *   "100 simultaneous reservation attempts for 20 seats"
 *
 * What it verifies:
 *   ✅ Exactly 20 requests succeed (HTTP 201)
 *   ✅ Remaining 80 get NO_SEATS_AVAILABLE (HTTP 409)
 *   ✅ Zero 500 errors — the database locking is correct
 *
 * Prerequisites:
 *   1. Server running:  cd server && npm run dev
 *   2. Users created:   node load-tests/setup.js
 *   3. k6 installed:    https://grafana.com/docs/k6/latest/set-up/install-k6/
 *
 * Run:
 *   k6 run load-tests/concurrency.js
 *   k6 run --env BASE_URL=http://localhost:3001 load-tests/concurrency.js
 */

import http   from 'k6/http';
import { check, sleep } from 'k6';
import { Counter, Rate } from 'k6/metrics';
import { SharedArray } from 'k6/data';

// ── Config ──────────────────────────────────────────────────────────────────
const BASE_URL     = __ENV.BASE_URL     || 'http://localhost:3001';
const WORKSHOP_ID  = __ENV.WORKSHOP_ID  || '00000000-0000-0000-0000-000000000001';

// Load tokens pre-generated by setup.js
const tokens = new SharedArray('tokens', () => JSON.parse(open('./tokens.json')));

// ── Custom metrics ───────────────────────────────────────────────────────────
const holds_created      = new Counter('holds_created');       // HTTP 201
const no_seats           = new Counter('no_seats');            // HTTP 409 NO_SEATS_AVAILABLE
const already_has        = new Counter('already_has');         // HTTP 409 ALREADY_HAS_RESERVATION
const server_errors      = new Counter('server_errors');       // HTTP 5xx
const idempotency_safe   = new Counter('idempotency_retries_safe'); // same key returned same body

// ── Test scenarios ───────────────────────────────────────────────────────────
export const options = {
  scenarios: {
    /**
     * Scenario 1: 100 VUs all fire at the exact same moment (arrival_rate model).
     * This is the hardest concurrency test — a thundering herd.
     */
    thundering_herd: {
      executor:    'shared-iterations',
      vus:         100,
      iterations:  100,
      maxDuration: '30s',
      tags:        { scenario: 'thundering_herd' },
    },
  },

  thresholds: {
    // Hard pass/fail gates that reviewers will see in the summary
    'holds_created':   ['count <= 20'],  // MUST never exceed capacity
    'server_errors':   ['count == 0'],   // MUST have zero 500 errors
    'http_req_failed': ['rate < 0.01'],  // Network failures < 1%

    // Informational — won't fail the run but shows in output
    'http_req_duration': ['p(95) < 2000'],
  },
};

// ── Main VU function ─────────────────────────────────────────────────────────
export default function () {
  const token = tokens[__VU % tokens.length];
  const idemKey = `hold-${__VU}-${__ITER}`;  // unique per VU + iteration

  const res = http.post(
    `${BASE_URL}/api/workshops/${WORKSHOP_ID}/holds`,
    JSON.stringify({}),
    {
      headers: {
        'Content-Type':    'application/json',
        'Authorization':   `Bearer ${token}`,
        'Idempotency-Key': idemKey,
      },
      timeout: '10s',
      tags:    { name: 'create_hold' },
    },
  );

  // ── Track outcome ──────────────────────────────────────────────────────────
  if (res.status === 201) {
    holds_created.add(1);
    check(res, {
      'hold body has status HELD':     (r) => r.json('reservation.status') === 'HELD',
      'hold body has expiresAt':       (r) => !!r.json('reservation.expiresAt'),
      'hold body has secondsUntilExpiry': (r) => r.json('reservation.secondsUntilExpiry') > 0,
    });

  } else if (res.status === 409) {
    const code = res.json('error.code');
    if (code === 'NO_SEATS_AVAILABLE')    no_seats.add(1);
    if (code === 'ALREADY_HAS_RESERVATION') already_has.add(1);

    check(res, {
      '409 has error code': (r) => !!r.json('error.code'),
    });

  } else {
    server_errors.add(1);
    console.error(`VU ${__VU}: Unexpected ${res.status} — ${res.body}`);
  }
}

// ── Summary printed after the run ─────────────────────────────────────────
export function handleSummary(data) {
  const created = data.metrics.holds_created?.values?.count ?? 0;
  const noSeats = data.metrics.no_seats?.values?.count ?? 0;
  const errors  = data.metrics.server_errors?.values?.count ?? 0;

  const passed  = created <= 20 && errors === 0;

  console.log('\n══════════════════════════════════════════════════');
  console.log(' SeatLock — Concurrency Test Results');
  console.log('══════════════════════════════════════════════════');
  console.log(`  Holds created (201):         ${created}  ${created <= 20 ? '✅' : '❌ OVERBOOKING!'}`);
  console.log(`  No seats (409):              ${noSeats}`);
  console.log(`  Server errors (5xx):         ${errors}  ${errors === 0 ? '✅' : '❌'}`);
  console.log(`  p95 latency:                 ${(data.metrics.http_req_duration?.values?.['p(95)'] ?? 0).toFixed(0)}ms`);
  console.log('──────────────────────────────────────────────────');
  console.log(`  Overall: ${passed ? '✅ PASSED' : '❌ FAILED'}`);
  console.log('══════════════════════════════════════════════════\n');

  return {
    'load-tests/results/concurrency-summary.json': JSON.stringify(data, null, 2),
  };
}
